import Ledger.Theorems

/-!
# L2: the free construction (reified morphisms)

The representation tower's first computable-shaped level: morphisms
are **terms** — one constructor per fundamental operation, plus one
per atomic generator — and the groupoid is the quotient of the term
type by exactly the congruence the laws generate (the "free" of the
worksheet's K1, made literal).

- `GenSpec` — a family of atomic generators with endpoints (what a
  parsed journal supplies).
- `FreeMor S A B` — the term language over `S`.
- `Rel` — the congruence: equivalence + per-operation congruence
  rules + one constructor per `𝕋Laws` equation (cast-transported
  where the law crosses an object equality) + the hom-set
  commutative-monoid laws (which the abstract 𝕋 gets from its
  `AddCommMonoid` instances, and the free model must therefore
  build).
- `FreeHom S A B` — the quotient; `freeT S : 𝕋`, `freeLaws S`.
- `freeGenerated S` — **`Generated` is a theorem here**, discharging
  decision D13's promise: at L2 the "generated by the journal's
  entries" hypothesis of the fundamental theorems is constructed,
  not assumed. Semantic equality on this level is `Rel` (via the
  quotient): `a ≡ b ⟺ ⟦a⟧ = ⟦b⟧` holds by construction.

Freeness proper (no equations beyond `Rel`) is witnessed one level
*down*: the flow denotation in `Pacioli.lean` separates terms that
`Rel` does not relate (e.g. the formal tensor-nonadditivity
counterexample), so the quotient is not degenerate.
-/

namespace Ledger

/-- A generator specification: the atomic transactions a journal
    declares, each with its source and target account multisets. -/
structure GenSpec where
  /-- The type of atomic transactions (journal entries). -/
  Gen : Type
  dom : Gen → Object
  cod : Gen → Object

namespace GenSpec

variable (S : GenSpec)

/-- Reified morphisms: the term language of 𝕋 over the generators.
    One constructor per fundamental operation — the free
    construction's standard move of promoting operations to
    constructors. -/
inductive FreeMor : Object → Object → Type where
  | gen (t : S.Gen) : FreeMor (S.dom t) (S.cod t)
  | id (A : Object) : FreeMor A A
  | zero (A B : Object) : FreeMor A B
  | comp {A B C : Object} (g : FreeMor B C) (f : FreeMor A B) : FreeMor A C
  | inv {A B : Object} (f : FreeMor A B) : FreeMor B A
  | tensor {A B C D : Object} (f : FreeMor A B) (g : FreeMor C D) :
      FreeMor (A + C) (B + D)
  | add {A B : Object} (f g : FreeMor A B) : FreeMor A B

variable {S}

/-- Transport a term along endpoint equalities. -/
def FreeMor.cast : {A A' B B' : Object} → A = A' → B = B' →
    S.FreeMor A B → S.FreeMor A' B'
  | _, _, _, _, rfl, rfl, f => f

/-- The congruence generated by the laws of 𝕋 — the *only* equations
    of the free model. -/
inductive Rel : {A B : Object} → S.FreeMor A B → S.FreeMor A B → Prop where
  -- equivalence
  | refl {A B : Object} (f : S.FreeMor A B) : Rel f f
  | symm {A B : Object} {f g : S.FreeMor A B} : Rel f g → Rel g f
  | trans {A B : Object} {f g h : S.FreeMor A B} :
      Rel f g → Rel g h → Rel f h
  -- congruence
  | comp_congr {A B C : Object} {g g' : S.FreeMor B C} {f f' : S.FreeMor A B} :
      Rel g g' → Rel f f' → Rel (.comp g f) (.comp g' f')
  | inv_congr {A B : Object} {f f' : S.FreeMor A B} :
      Rel f f' → Rel (.inv f) (.inv f')
  | tensor_congr {A B C D : Object}
      {f f' : S.FreeMor A B} {g g' : S.FreeMor C D} :
      Rel f f' → Rel g g' → Rel (.tensor f g) (.tensor f' g')
  | add_congr {A B : Object} {f f' g g' : S.FreeMor A B} :
      Rel f f' → Rel g g' → Rel (.add f g) (.add f' g')
  -- category
  | comp_assoc {A B C D : Object}
      (h : S.FreeMor C D) (g : S.FreeMor B C) (f : S.FreeMor A B) :
      Rel (.comp h (.comp g f)) (.comp (.comp h g) f)
  | id_comp {A B : Object} (f : S.FreeMor A B) : Rel (.comp (.id B) f) f
  | comp_id {A B : Object} (f : S.FreeMor A B) : Rel (.comp f (.id A)) f
  -- groupoid
  | inv_comp {A B : Object} (f : S.FreeMor A B) :
      Rel (.comp (.inv f) f) (.id A)
  | comp_inv {A B : Object} (f : S.FreeMor A B) :
      Rel (.comp f (.inv f)) (.id B)
  -- monoidal
  | tensor_id (A B : Object) :
      Rel (.tensor (.id A) (.id B)) (.id (A + B))
  | tensor_comp {A B C A' B' C' : Object}
      (g : S.FreeMor B C) (f : S.FreeMor A B)
      (g' : S.FreeMor B' C') (f' : S.FreeMor A' B') :
      Rel (.comp (.tensor g g') (.tensor f f'))
          (.tensor (.comp g f) (.comp g' f'))
  | tensor_assoc {A B C D E F : Object}
      (f : S.FreeMor A B) (g : S.FreeMor C D) (h : S.FreeMor E F) :
      Rel ((FreeMor.tensor (FreeMor.tensor f g) h).cast
            (add_assoc A C E) (add_assoc B D F))
          (.tensor f (.tensor g h))
  | tensor_comm {A B C D : Object}
      (f : S.FreeMor A B) (g : S.FreeMor C D) :
      Rel ((FreeMor.tensor f g).cast (add_comm A C) (add_comm B D))
          (.tensor g f)
  | tensor_unit {A B : Object} (f : S.FreeMor A B) :
      Rel ((FreeMor.tensor f (.id 0)).cast (add_zero A) (add_zero B)) f
  -- hom-set commutative monoid
  | add_comm {A B : Object} (f g : S.FreeMor A B) :
      Rel (.add f g) (.add g f)
  | add_assoc {A B : Object} (f g h : S.FreeMor A B) :
      Rel (.add (.add f g) h) (.add f (.add g h))
  | add_zero {A B : Object} (f : S.FreeMor A B) :
      Rel (.add f (.zero A B)) f

instance relSetoid (S : GenSpec) (A B : Object) : Setoid (S.FreeMor A B) :=
  ⟨Rel, fun f => Rel.refl f, Rel.symm, Rel.trans⟩

/-- L2 hom-sets: terms up to exactly the structural laws. -/
abbrev FreeHom (S : GenSpec) (A B : Object) : Type :=
  Quotient (relSetoid S A B)

instance (S : GenSpec) (A B : Object) : Zero (FreeHom S A B) :=
  ⟨⟦.zero A B⟧⟩

instance (S : GenSpec) (A B : Object) : Add (FreeHom S A B) :=
  ⟨Quotient.map₂ .add fun _ _ hf _ _ hg => Rel.add_congr hf hg⟩

instance (S : GenSpec) (A B : Object) : AddCommMonoid (FreeHom S A B) where
  add_assoc x y z :=
    Quotient.inductionOn₃ x y z fun f g h =>
      Quotient.sound (Rel.add_assoc f g h)
  add_comm x y :=
    Quotient.inductionOn₂ x y fun f g =>
      Quotient.sound (Rel.add_comm f g)
  add_zero x :=
    Quotient.inductionOn x fun f => Quotient.sound (Rel.add_zero f)
  zero_add x :=
    Quotient.inductionOn x fun f =>
      Quotient.sound ((Rel.add_comm _ _).trans (Rel.add_zero f))
  nsmul := nsmulRec

/-- The free model of 𝕋 over a generator specification. -/
def freeT (S : GenSpec) : 𝕋 where
  Hom := FreeHom S
  homAddCommMonoid _ _ := inferInstance
  id A := ⟦.id A⟧
  comp := Quotient.map₂ .comp fun _ _ hg _ _ hf => Rel.comp_congr hg hf
  inv := Quotient.map .inv fun _ _ hf => Rel.inv_congr hf
  tensor := Quotient.map₂ .tensor fun _ _ hf _ _ hg => Rel.tensor_congr hf hg

/-- Transport on the quotient is transport on representatives. -/
theorem castHom_mk {S : GenSpec} {A A' B B' : Object}
    (hA : A = A') (hB : B = B') (f : S.FreeMor A B) :
    (freeT S).castHom hA hB (⟦f⟧ : FreeHom S A B) = ⟦f.cast hA hB⟧ := by
  subst hA; subst hB; rfl

/-- The free model satisfies every law — each equation is its `Rel`
    constructor, transported through the quotient. -/
def freeLaws (S : GenSpec) : 𝕋Laws (freeT S) where
  comp_assoc h g f :=
    Quotient.inductionOn₃ h g f fun h g f =>
      Quotient.sound (Rel.comp_assoc h g f)
  id_comp f := Quotient.inductionOn f fun f => Quotient.sound (Rel.id_comp f)
  comp_id f := Quotient.inductionOn f fun f => Quotient.sound (Rel.comp_id f)
  inv_comp f := Quotient.inductionOn f fun f => Quotient.sound (Rel.inv_comp f)
  comp_inv f := Quotient.inductionOn f fun f => Quotient.sound (Rel.comp_inv f)
  tensor_id A B := Quotient.sound (Rel.tensor_id A B)
  tensor_comp g f g' f' :=
    Quotient.inductionOn₂ g f fun g f =>
      Quotient.inductionOn₂ g' f' fun g' f' =>
        Quotient.sound (Rel.tensor_comp g f g' f')
  tensor_assoc f g h :=
    Quotient.inductionOn₃ f g h fun f g h =>
      𝕋.heq_of_castHom_eq _ _
        ((castHom_mk _ _ _).trans (Quotient.sound (Rel.tensor_assoc f g h)))
  tensor_comm f g :=
    Quotient.inductionOn₂ f g fun f g =>
      𝕋.heq_of_castHom_eq _ _
        ((castHom_mk _ _ _).trans (Quotient.sound (Rel.tensor_comm f g)))
  tensor_unit f :=
    Quotient.inductionOn f fun f =>
      𝕋.heq_of_castHom_eq _ _
        ((castHom_mk _ _ _).trans (Quotient.sound (Rel.tensor_unit f)))

/-- **Generatedness is a theorem at L2** (decision D13 discharged):
    the free model is generated by its `gen` terms — induction over
    the quotient is structural induction over terms. -/
def freeGenerated (S : GenSpec) : 𝕋.Generated (freeT S) where
  IsGen {A B} f :=
    ∃ (t : S.Gen) (hA : S.dom t = A) (hB : S.cod t = B),
      f = (freeT S).castHom hA hB ⟦.gen t⟧
  induction := fun P hgen hid hzero hcomp hinv htensor hadd {A B} q => by
    refine Quotient.inductionOn q fun x => ?_
    clear q
    induction x with
    | gen t => exact hgen _ ⟨t, rfl, rfl, rfl⟩
    | id A₀ => exact hid A₀
    | zero A₀ B₀ => exact hzero A₀ B₀
    | comp g₀ f₀ ihg ihf => exact hcomp ⟦g₀⟧ ⟦f₀⟧ ihg ihf
    | inv f₀ ihf => exact hinv ⟦f₀⟧ ihf
    | tensor f₀ g₀ ihf ihg => exact htensor ⟦f₀⟧ ⟦g₀⟧ ihf ihg
    | add f₀ g₀ ihf ihg => exact hadd ⟦f₀⟧ ⟦g₀⟧ ihf ihg

/-- Semantic-equality exhibit: the quotient really identifies what
    the laws identify (`f + 0 ≡ f`). -/
example {S : GenSpec} {A B : Object} (f : S.FreeMor A B) :
    (⟦.add f (.zero A B)⟧ : FreeHom S A B) = ⟦f⟧ :=
  Quotient.sound (Rel.add_zero f)

end GenSpec

end Ledger
